### ISSUE TITLE
Failed to run with vite

### ISSUE THREAD

**Issue by freewind** [HorusGoul/vite-plugin-stylex#65]
```
cd vite-plugin-stylex/apps/vite-demo
pnpm i
pnpm run dev
```

Throws error:

```
> vite-demo@0.0.0 dev /Users/freewind/workspace/vite-plugin-stylex/apps/vite-demo
> vite

✘ [ERROR] Failed to resolve entry for package "vite-plugin-stylex". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]

    ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28725:11)
    at resolvePackageEntry (file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28722:5)
    at tryNodeResolve (file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28453:20)
    at resolveByViteResolver (file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66232:32)
    at file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66273:40
    at requestCallbacks.on-resolve (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:28)
    at handleRequest (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)

  This error came from the "onResolve" callback registered
  here:

    ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66258:27)
    at handlePlugins (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)
    at /Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2177:15
    at new Promise (<anonymous>)
    at Object.build (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2176:25)
    at build (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2025:51)
    at bundleConfigFile (file:///Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/vite@4.5.3_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66209:26)

  The plugin "externalize-deps" was triggered by this
  import

    vite.config.ts:3:19:
      3 │ import styleX from "vite-plugin-stylex";
        ╵                    ~~~~~~~~~~~~~~~~~~~~

failed to load config from /Users/freewind/workspace/vite-plugin-stylex/apps/vite-demo/vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "vite-plugin-stylex". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/freewind/workspace/vite-plugin-stylex/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by HorusGoul** [comment]
You probably didn't build the `vite-plugin-stylex`:

```bash
cd packages/vite-plugin-stylex
pnpm build
```
