### ISSUE TITLE
React strict dom, adding to importSources  generates Error: Package subpath './babel' is not defined by "exports"

### ISSUE THREAD

**Issue by lotusjohn** [HorusGoul/vite-plugin-stylex#93]
Hi,
having issue with using rsd in a web project. 
Adding this, according to the instructions generates the below error. 
This is logged when trying to run in dev, and it also logs the same error during build. 

If I remove the importSources stuff, it works to run dev and to build. 

**Added to vite config**
```
styleX({
      importSources: [
        {
          from: "react-strict-dom",
          as: "css",
        },
      ],
    }),
```

**Output**
```
Error: Package subpath './babel' is not defined by "exports" in /Users/j/Dev/projectName/node_modules/react-strict-dom/package.json

 at exportsNotFound (node:internal/modules/esm/resolve:296:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:643:9)
    at resolveExports (node:internal/modules/cjs/loader:640:36)
    at Function._findPath (node:internal/modules/cjs/loader:748:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1235:27)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at TransformPluginContext.transform (file:///Users/j/Dev/projectName/node_modules/vite-plugin-stylex/src/main.mts:338:35)
    at PluginContainer.transform (file:///Users/j/Dev/projectName/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49097:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at loadAndTransform (file:///Users/j/Dev/projectName/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51929:27)
    at instantiateModule (file:///Users/j/Dev/projectName/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:52874:44)
```

**Versions of deps** 
```
"react": "18.3.1",
"react-dom": "18.3.1",
"react-strict-dom": "0.0.29",
"vite-plugin-stylex": "^0.13.0",
"vite": "^5.4.10",
"@stylexjs/stylex": "^0.9.3",
```

**Comment by HorusGoul** [comment]
I've opened an issue in the `react-strict-dom` repository because one of the exports we used was removed. 

For now, please downgrade to `react-strict-dom@0.0.28`, which should serve as a workaround while we figure out how to support RSD after this update :smile:

**Comment by carloslibardo** [comment]
@HorusGoul downgrade to 0.0.28 does not work for me, only works at 0.0.27. When running ```npm create vite@latest my-react-app -- --template react-ts``` and installing [react-strict-dom](https://github.com/facebook/react-strict-dom) i'm getting this error:

```Error: 'stylex.create' should never be called at runtime. It should be compiled away by '@stylexjs/babel-plugin```

I tried to use vite-plugin-stylex and add styleX config to vite.config, but the error changes to the same as this issue.

I think is related to https://github.com/facebook/react-strict-dom/issues/240.
